name: FTC Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      # Use JDK 17 so sdkmanager works, but tell Gradle to compile with 11
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set FTC Gradle to Java 11
        run: echo "org.gradle.java.home=/usr/lib/jvm/temurin-11-jdk-amd64" >> gradle.properties

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Assemble Debug APK
        run: ./gradlew --no-daemon :FtcRobotController:assembleDebug

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: '**/build/outputs/apk/debug/*.apk'
